version: 0.2

env:
  variables:
    SOLUTION: .\HelloWorldWebCore.sln
    DOTNET_FRAMEWORK: 4.8

phases:
  build:
    commands:
      - dotnet test ./HelloWorldWebCore.sln
      - dotnet publish -c release -o ./build_output ./HelloWorldWebCore.csproj
artifacts:
  files:
    - .\HelloWorldWebCore\bin\Debug\*
