version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build: 
    commands:
      - dotnet restore ./src/HelloWorldWebCore/HelloWorldWebCore.csproj
  build:
    commands:
      - dotnet build ./src/HelloWorldWebCore/HelloWorldWebCore.csproj
  post_build:
    commands:
      - dotnet publish -c release -o ./build_output ./src/HelloWorldWebCore/HelloWorldWebCore.csproj
artifacts:
  files:
    - src/HelloWorldWebCore/build_output/*
    - appspec.yml
    - installApp.sh
