version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: latest
  build:
    commands:
      - dotnet test ./src/HelloWorldWebCore/HelloWorldWebCore.csproj
      - dotnet publish -c release -o ./build_output ./src/HelloWorldWebCore/HelloWorldWebCore.csproj
artifacts:
  files:
    - src/HelloWorldWebCore/build_output/*
    - appspec.yml
    - installApp.sh
