version: 0.2
phases:
   pre_build
       commands:
          - echo Restore started on 'date'
          - dotnet restore ./src/HelloWorldWebCore/HelloWorldWebCore.csproj
   build:
       commands:
          - echo Build started on 'date'
          - dotnet publish -c release -o ./build_output ./src/HelloWorldWebCore/HelloWorldWebCore.csproj
artifacts:
   files:
      - HelloWorldWebCore/build_output/**/*
      - appspec.yml
      - installApp.sh
