version: 0.2

phases:
  build:
    commands:
      - dotnet test ./HelloWorldWebCore.sln
      - dotnet publish -c release -o ./build_output ./HelloWorldWebCore.sln
artifacts:
  files:
    - src/HelloWorldWebCore/build_output/*
    - appspec.yml
    - installApp.sh
